version: '3.9'
services:
  web:
    build:
      context: .
      args:
        VITE_USE_MOCK: "false"
        VITE_API_BASE_URL: "http://localhost:8080"
    ports:
      - '5173:4173'
    depends_on:
      - backend
  backend:
    build:
      context: ../Lab4_Castelblanco_Gomez
    ports:
      - '8080:8080'